/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_csnc_burp_jwtscanner_Gmp */

#ifndef _Included_ch_csnc_burp_jwtscanner_Gmp
#define _Included_ch_csnc_burp_jwtscanner_Gmp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_csnc_burp_jwtscanner_Gmp
 * Method:    sub
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_csnc_burp_jwtscanner_Gmp_sub
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ch_csnc_burp_jwtscanner_Gmp
 * Method:    cdiv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_csnc_burp_jwtscanner_Gmp_cdiv
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ch_csnc_burp_jwtscanner_Gmp
 * Method:    pow
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_csnc_burp_jwtscanner_Gmp_pow
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ch_csnc_burp_jwtscanner_Gmp
 * Method:    powm
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_csnc_burp_jwtscanner_Gmp_powm
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     ch_csnc_burp_jwtscanner_Gmp
 * Method:    gcd
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_csnc_burp_jwtscanner_Gmp_gcd
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
